name: CI
on: [push, pull_request]

jobs:

  test_postgres:
    name: Node ${{ matrix.node }}, Postgres ${{ matrix.postgres-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['20']
        postgresql-version: [16]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Start Postgres v${{ matrix.postgresql-version }}
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: ${{ matrix.postgresql-version }}
          postgresql user: postgres
          postgresql password: 12345
          postgresql db: 'acl_test'

      - run: npm install
      - run: node setup.js 'acl_test' 'postgres' '12345' 'acl_' 'localhost'
      - run: npm run test_knex
